// OLPW:subjects.js | script for subjects
window.OLPW_MORE_SUBJECTS =[
    {
        "slug": "economics",
        "name": "Economics",
        "short": "Economics",
        "card": "Markets, money, trade and government policy.",
        "color": "#10B981",
        "chapters": [
            "The Basic Economic Problem",
            "The Allocation of Resources",
            "Demand and Supply",
            "Price Determination and Elasticity",
            "Market Failure",
            "Money and Banking",
            "Households: Spending, Saving and Borrowing",
            "Workers and Trade Unions",
            "Firms and Production",
            "Market Structure",
            "Government and the Macroeconomy",
            "Economic Growth, Employment and Inflation",
            "Economic Development",
            "International Trade and Globalisation",
            "National Income & the Macroeconomy",
            "Inflation & Unemployment in Depth",
            "The Balance of Payments & Exchange Rates",
            "Globalisation & Development Economics"
        ]
    },
    {
        "slug": "accounting",
        "name": "Accounting",
        "short": "Accounting",
        "card": "Double entry, ledgers and final accounts.",
        "color": "#0EA5E9",
        "chapters": [
            "The Fundamentals of Accounting",
            "Sources and Recording of Data",
            "Double-Entry Bookkeeping",
            "The Cash Book and Petty Cash",
            "The Trial Balance",
            "Correction of Errors",
            "Bank Reconciliation",
            "Control Accounts",
            "Accounting Principles",
            "Accruals, Prepayments and Depreciation",
            "Irrecoverable Debts and Provisions",
            "Financial Statements of Sole Traders",
            "Partnerships and Limited Companies",
            "Analysis and Interpretation",
            "Manufacturing Accounts",
            "Incomplete Records",
            "Clubs & Societies"
        ]
    },
    {
        "slug": "business",
        "name": "Business Studies",
        "short": "Business",
        "card": "Enterprise, marketing, operations and finance.",
        "color": "#F97316",
        "chapters": [
            "Understanding Business Activity",
            "Types of Business Organisation",
            "Business Objectives and Stakeholders",
            "Business Growth and Size",
            "Motivating Workers",
            "Organisation and Management",
            "Recruitment, Training and Communication",
            "Marketing and Market Research",
            "The Marketing Mix",
            "Production and Efficiency",
            "Costs, Break-even and Quality",
            "Sources of Finance and Cash Flow",
            "Financial Statements",
            "The External Environment",
            "Business & the International Economy"
        ]
    },
    {
        "slug": "commerce",
        "name": "Commerce",
        "short": "Commerce",
        "card": "Trade, retail, transport and insurance.",
        "color": "#EAB308",
        "chapters": [
            "Production and Trade",
            "Retail Trade",
            "Wholesale Trade",
            "Documents of Trade",
            "Consumer Protection",
            "International Trade",
            "Import and Export Procedures",
            "Transport",
            "Communication",
            "Warehousing",
            "Advertising",
            "Banking",
            "Insurance",
            "Business Units and the Stock Exchange",
            "Chambers of Commerce & Trade Associations",
            "E-commerce & Modern Trading Methods",
            "Business Finance & Sources of Capital",
            "Entrepreneurship & the Business Environment"
        ]
    },
    {
        "slug": "english",
        "name": "English Language",
        "short": "English",
        "card": "Reading, writing and exam technique.",
        "color": "#6366F1",
        "chapters": [
            "Reading for Meaning",
            "Writer's Craft and Language Effects",
            "Summary Writing",
            "Directed Writing",
            "Descriptive Writing",
            "Narrative Writing",
            "Argumentative and Discursive Writing",
            "Persuasive Techniques",
            "Grammar and Sentence Structure",
            "Punctuation and Accuracy",
            "Vocabulary and Word Choice",
            "Comparing Texts",
            "Speaking and Listening",
            "Exam Technique",
            "Comprehension: Inference, Tone and Attitude",
            "Directed Writing: Register, Form and Purpose",
            "Crafting Descriptive and Narrative Prose",
            "Argumentative and Discursive Mastery"
        ]
    },
    {
        "slug": "literature",
        "name": "Literature in English",
        "short": "Literature",
        "card": "Poetry, prose, drama and analysis.",
        "color": "#A855F7",
        "chapters": [
            "Introduction to Literary Study",
            "Poetic Form and Structure",
            "Poetic Language and Imagery",
            "Rhyme, Rhythm and Metre",
            "Prose: Narrative and Point of View",
            "Characterisation",
            "Setting and Atmosphere",
            "Themes and Ideas",
            "Drama: Stagecraft",
            "Shakespeare and Tragedy",
            "Context",
            "Structure and Plot",
            "Unseen Texts",
            "Writing Literature Essays",
            "Studying Set Poems: Text-Level Analysis",
            "Set Novels and Plays: Studying at Text Level",
            "Comparative Essays and Critical Perspectives",
            "Writing Literature Essays Under Time Pressure"
        ]
    },
    {
        "slug": "add-maths",
        "name": "Additional Mathematics",
        "short": "Add Maths",
        "card": "Functions, calculus and trigonometry.",
        "color": "#EF4444",
        "chapters": [
            "Functions",
            "Quadratic Functions",
            "Equations, Inequalities and Graphs",
            "Factors of Polynomials",
            "Indices and Surds",
            "Logarithmic and Exponential Functions",
            "Straight Line Graphs",
            "Circular Measure",
            "Trigonometry",
            "Permutations and Combinations",
            "Series",
            "Vectors in Two Dimensions",
            "Differentiation",
            "Integration and Kinematics",
            "Applications of Differentiation",
            "Applications of Integration",
            "Coordinate Geometry of the Circle",
            "Trigonometric Identities and Equations in Depth"
        ]
    },
    {
        "slug": "statistics",
        "name": "Statistics",
        "short": "Statistics",
        "card": "Data, averages, probability and correlation.",
        "color": "#14B8A6",
        "chapters": [
            "Collecting Data",
            "Sampling Techniques",
            "Questionnaires and Surveys",
            "Tabulation and Classification",
            "Diagrams and Charts",
            "Histograms and Frequency Polygons",
            "Cumulative Frequency",
            "Measures of Central Tendency",
            "Measures of Dispersion",
            "Probability",
            "Conditional Probability",
            "Correlation and Regression",
            "Index Numbers",
            "Time Series and Moving Averages",
            "Discrete Random Variables and Expectation",
            "Transformations of Mean and Standard Deviation",
            "Crude and Standardised Rates",
            "The Statistical Enquiry Cycle and Exam Practice"
        ]
    },
    {
        "slug": "geography",
        "name": "Geography",
        "short": "Geography",
        "card": "Population, landforms, climate and development.",
        "color": "#22C55E",
        "chapters": [
            "Population Dynamics",
            "Migration",
            "Settlement and Urbanisation",
            "Plate Tectonics",
            "Rivers",
            "Coasts",
            "Weather",
            "Climate and Natural Vegetation",
            "Environmental Risks and Benefits",
            "Development",
            "Food Production",
            "Industry",
            "Tourism",
            "Energy and Water",
            "Weathering & Soils",
            "Ecosystems & Natural Vegetation in Depth",
            "Mapwork & Fieldwork Skills",
            "Development Indicators, Aid & Human Welfare in Depth"
        ]
    },
    {
        "slug": "history",
        "name": "History",
        "short": "History",
        "card": "20th-century world and source skills.",
        "color": "#B45309",
        "chapters": [
            "Causes of the First World War",
            "The Treaty of Versailles",
            "The League of Nations",
            "The Failure of the League",
            "The Road to the Second World War",
            "Origins of the Cold War",
            "The Berlin Blockade and Divided Germany",
            "The Korean War",
            "The Cuban Missile Crisis",
            "The Vietnam War",
            "Decolonisation",
            "The United Nations",
            "The End of the Cold War",
            "Source Analysis Skills",
            "The Russian Revolution & Stalin's USSR 1917-1941",
            "The USA 1919-1941",
            "The Struggle for Independence in South Asia 1900-1971",
            "China 1900-1976"
        ]
    },
    {
        "slug": "ict",
        "name": "ICT",
        "short": "ICT",
        "card": "Hardware, networks, safety and software.",
        "color": "#3B82F6",
        "chapters": [
            "Types and Components of Computer Systems",
            "Input and Output Devices",
            "Storage Devices and Media",
            "Networks and Communication",
            "The Effects of Using IT",
            "ICT Applications",
            "Systems Life Cycle",
            "Safety and Security",
            "Audiences and Communication",
            "File Management and Images",
            "Databases",
            "Spreadsheets",
            "Document Production and Presentations",
            "Website Authoring",
            "Emerging Technologies",
            "Programming & Computational Thinking",
            "Creating Digital Media",
            "Integrated ICT Project & Exam Technique"
        ]
    },
    {
        "slug": "sociology",
        "name": "Sociology",
        "short": "Sociology",
        "card": "Society, family, education and crime.",
        "color": "#EC4899",
        "chapters": [
            "Introduction to Sociology",
            "Research Methods",
            "Culture, Identity and Socialisation",
            "Social Control",
            "Social Stratification",
            "Gender and Ethnicity",
            "The Family",
            "Changes in Family Life",
            "Education",
            "Inequality in Education",
            "Crime and Deviance",
            "Explaining Crime",
            "The Media",
            "Power, Politics and Religion",
            "Research Methods in Depth",
            "Globalisation & Social Change",
            "Health, Medicine & the Sick Role",
            "Work, Unemployment & the Economy"
        ]
    },
    {
        "slug": "environmental",
        "name": "Environmental Management",
        "short": "Env. Management",
        "card": "Resources, pollution and sustainability.",
        "color": "#16A34A",
        "chapters": [
            "Environmental Systems",
            "Rocks and Minerals",
            "Energy Resources",
            "Agriculture and the Environment",
            "Water and Its Management",
            "Oceans and Fisheries",
            "Managing Natural Hazards",
            "The Atmosphere",
            "Atmospheric Pollution",
            "Climate Change",
            "Ecosystems",
            "Biodiversity and Conservation",
            "Deforestation",
            "Sustainable Management",
            "Human Population and Carrying Capacity",
            "Water Scarcity, Irrigation and Dams",
            "Oceans and Coasts - Pollution and Fisheries Management",
            "Environmental Impact Assessment, Legislation and International Agreements"
        ]
    },
    {
        "slug": "global-perspectives",
        "name": "Global Perspectives",
        "short": "Global Persp.",
        "card": "Research, reasoning and global issues.",
        "color": "#0891B2",
        "chapters": [
            "Introduction to Global Perspectives",
            "Critical Thinking",
            "Evaluating Sources",
            "Research Skills",
            "Collaboration and Teamwork",
            "Reflection",
            "Poverty and Inequality",
            "Climate Change and Sustainability",
            "Health and Wellbeing",
            "Technology and Society",
            "Human Rights",
            "Globalisation and Trade",
            "Conflict and Peace",
            "Written Reports and Presentations",
            "Choosing a Team Project Topic",
            "Research & Evidence for the Individual Report",
            "Writing a High-Level Individual Report",
            "Presentation & Discussion Skills"
        ]
    },
    {
        "slug": "bangladesh-studies",
        "name": "Bangladesh Studies",
        "short": "BD Studies",
        "card": "History, culture and geography of Bangladesh.",
        "color": "#059669",
        "chapters": [
            "Ancient Bengal",
            "Muslim Rule in Bengal",
            "British Rule in Bengal",
            "The Pakistan Movement",
            "The Language Movement",
            "Political Developments 1954–1969",
            "The Liberation War of 1971",
            "Location and Physical Features of Bangladesh",
            "Rivers and Climate",
            "Natural Hazards in Bangladesh",
            "Agriculture",
            "Natural Resources and Energy",
            "Industry and the Economy",
            "Population, Transport and Environment",
            "Constitution, Government & Culture"
        ]
    },
    {
        "slug": "bangla",
        "name": "Bangla",
        "short": "Bangla",
        "card": "Grammar, comprehension and composition.",
        "color": "#DC2626",
        "chapters": [
            "Bangla Alphabet and Sounds",
            "Parts of Speech",
            "Sandhi (Joining of Sounds)",
            "Samas (Compound Words)",
            "Karak and Bibhakti",
            "Synonyms, Antonyms and Idioms",
            "Sentence Structure and Transformation",
            "Spelling and Punctuation",
            "Reading Comprehension",
            "Translation",
            "Letter and Application Writing",
            "Essay Writing",
            "Story and Dialogue Writing",
            "Bangla Literature",
            "History of Bangla Literature and Movements",
            "Major Writers and Poets of Bangla",
            "Advanced Grammar: Bibhakti in Depth and Sentence Correction",
            "Précis, Expansion and Summary Skills"
        ]
    },
    {
        "slug": "islamiyat",
        "name": "Islamiyat",
        "short": "Islamiyat",
        "card": "Qur'an, Hadith, Seerah and beliefs.",
        "color": "#0D9488",
        "chapters": [
            "The Qur'an: Revelation and Compilation",
            "Themes of the Qur'an",
            "The Qur'an as a Source of Law",
            "Life of the Prophet in Makkah",
            "The Hijrah and Life in Madinah",
            "Battles of Early Islam",
            "The Conquest of Makkah and Final Years",
            "The Prophet's Family and Companions",
            "Hadith: Compilation and Importance",
            "The Rightly Guided Caliphs",
            "Articles of Faith",
            "Pillars of Islam: Shahadah and Salah",
            "Pillars of Islam: Zakah, Sawm and Hajj",
            "Islam and Society",
            "The Rightly Guided Caliphs in Depth",
            "Islamic Law and Jurisprudence (Usul al-Fiqh)",
            "Later Islamic History: Umayyad and Abbasid Contributions",
            "Islam in the Contemporary World"
        ]
    },
    {
        "slug": "travel-tourism",
        "name": "Travel and Tourism",
        "short": "Travel & Tourism",
        "card": "Tourism industry, destinations and marketing.",
        "color": "#F59E0B",
        "chapters": [
            "The Travel and Tourism Industry",
            "Growth of Tourism",
            "Tourism Sectors",
            "Destinations",
            "The Destination Life Cycle",
            "Customer Service",
            "Working in Travel and Tourism",
            "Marketing and Promotion",
            "Pricing and Products",
            "Economic Impacts of Tourism",
            "Social and Cultural Impacts",
            "Environmental Impacts",
            "Sustainable Tourism",
            "Tourism Planning and Development",
            "Transport Operations in Travel & Tourism",
            "Accommodation & Hospitality Operations",
            "Events, Conferences & Visitor Attractions",
            "Niche & Specialised Tourism"
        ]
    },
    {
        "slug": "art-design",
        "name": "Art and Design",
        "short": "Art & Design",
        "card": "Elements, media, artists and portfolio.",
        "color": "#E11D48",
        "chapters": [
            "The Formal Elements",
            "Colour Theory",
            "Composition",
            "Drawing Skills",
            "Perspective and Proportion",
            "Painting Techniques",
            "Printmaking",
            "Three-Dimensional Work",
            "Photography and Digital Media",
            "Art Movements",
            "Artist Research and Analysis",
            "Developing Ideas",
            "Assessment Objectives",
            "Portfolio and Exam Preparation",
            "Writing About Art: Critical and Historical Studies",
            "Developing a Personal Investigation",
            "The Timed Examination: Planning and Execution",
            "Experimental and Mixed-Media Approaches"
        ]
    },
    {
        "slug": "design-technology",
        "name": "Design and Technology",
        "short": "D&T",
        "card": "Design process, materials and manufacture.",
        "color": "#64748B",
        "chapters": [
            "The Design Process",
            "Research and Analysis",
            "Generating and Developing Ideas",
            "Woods",
            "Metals",
            "Plastics",
            "Smart and Modern Materials",
            "Tools and Equipment",
            "Joining and Finishing",
            "Manufacturing Processes",
            "CAD and CAM",
            "Mechanisms",
            "Electronics and Systems",
            "Sustainability and Evaluation",
            "Mechanisms in Depth",
            "Scales of Production",
            "Product Analysis & Disassembly",
            "Design Communication"
        ]
    },
    {
        "slug": "food-nutrition",
        "name": "Food and Nutrition",
        "short": "Food & Nutrition",
        "card": "Nutrients, diet, food science and safety.",
        "color": "#84CC16",
        "chapters": [
            "Introduction to Nutrition",
            "Proteins",
            "Carbohydrates and Fats",
            "Vitamins and Minerals",
            "Digestion and Energy",
            "Diet and Health",
            "Nutrition Through Life",
            "Food Commodities",
            "Food Science",
            "Cooking Methods",
            "Food Spoilage and Preservation",
            "Food Hygiene and Safety",
            "Meal Planning",
            "Consumer Education",
            "Protein Function in Cookery",
            "Flour, Pastry, Cake and Bread Making",
            "Nutrition for Sport, Pregnancy and Special Diets",
            "Food Labelling, Storage and Legislation"
        ]
    },
    {
        "slug": "physical-education",
        "name": "Physical Education",
        "short": "PE",
        "card": "Anatomy, fitness, training and sport.",
        "color": "#F43F5E",
        "chapters": [
            "The Skeletal System",
            "The Muscular System",
            "Movement and Levers",
            "The Cardiovascular System",
            "The Respiratory System",
            "Energy Systems",
            "Health, Fitness and Wellbeing",
            "Components of Fitness",
            "Principles of Training",
            "Methods of Training",
            "Diet, Injury and Safety",
            "Skill Acquisition",
            "Sport Psychology",
            "Social and Cultural Influences",
            "Exercise Physiology: Acute and Chronic Responses",
            "Biomechanics in Sport",
            "Performance Analysis and Talent Development",
            "Contemporary Issues in Sport"
        ]
    }
];
